### ISSUE TITLE
every time I read a Json I get internal error warning on R_decompress1

### ISSUE THREAD

**Issue by verajosemanuel** [ropenscilabs/roomba#70]
anytime I use roomba and using xml2 package without roomba (I had to uninstall to use xml2 properly):
Warning messages:
1: In get(Info[i, 1], envir = env) : internal error -3 in R_decompress1
2: In get(Info[i, 1], envir = env) : internal error -3 in R_decompress1
3: In get(Info[i, 1], envir = env) : internal error -3 in R_decompress1
4: In get(Info[i, 1], envir = env) : internal error -3 in R_decompress1

**Comment by jimhester** [comment]
I don't think there is an issue with the package, maybe your install was corrupted, likely re-installing would fix it.
