### ISSUE TITLE
Move hexsticker up to the level of the package name in README

### ISSUE THREAD

**Issue by g-velasq** [ropenscilabs/roomba#71]
Hello `roomba` team, excellent work!

This is a minor suggestion to move the hexsticker up to the level of the package name in the README, to match e.g. the janitor package (among others):

![image](https://user-images.githubusercontent.com/20712598/40633772-c68b1bc2-62bf-11e8-9ba3-2b4dc56215aa.png)

If there's support for this, I would be happy to put in a PR, along the lines of:

`# roomba <img src="./img/sticker.png" height="200px" align="right" />`

**Comment by aedobbyn** [comment]
Ah thank you so much! The hex sticker was added in a bit of a rush so didn't have time to look up the css people tend to use for sticker placement. Submit away!
