### ISSUE TITLE
Depending on roomba

### ISSUE THREAD

**Issue by sfirke** [ropenscilabs/roomba#75]
I am writing an R API package and, playing with roomba, it will save me a bunch of thinking and lines of code to snarf the data I want.  What is your reaction to me wanting to depend on roomba?

I guess that's a general question so more specifically, how likely is it that roomba would make it to CRAN some day and how far away from CRAN-ready is it?

And then other options I see are, I could build initially with roomba and then later replace with more explicit parsing of the nested data, or house roomba code internally to the package.

I love this package and value your opinions about how to appropriately make the most of it! 🙏

**Comment by aedobbyn** [comment]
Hey @sfirke -- thanks for the heads up! Very low chance that roomba will ever make it to CRAN. I think your idea of depending on roomba before figuring out a different solution is fine. It's not leaving GitHub any time soon :)

**Comment by sfirke** [comment]
Sounds good, I will proceed that way and if I have further ideas or questions will re-open this.  Thanks again for the handy package!
